import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { useCallback } from "react";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Handler for the navbar button
  const handleConnectWallet = useCallback(async () => {
    const walletName = "mnLace";
    try {
      // @ts-expect-error
      const api = await window.midnight?.[walletName]?.enable();
      console.log("Wallet API available:", api);
    } catch (error) {
      console.log("an error occurred", error);
    }
  }, []);

  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
